global:
  scrape_interval: 15s # ดึงข้อมูลทุกๆ 15 วินาที
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'safebreathe_app'
    static_configs:
      # ใช้ host.docker.internal เพื่อให้ Container วิ่งกลับมาหา Flask ที่รันอยู่บนเครื่องคุณ (port 5000)
      - targets: ['web:5000']