apiVersion: v1
kind: Service
metadata:
  name: pm-alert-service
  namespace: dustwatch
spec:
  type: NodePort
  selector:
    app: pm-alert
  ports:
    - protocol: TCP
      port: 80         # พอร์ตของ Service
      targetPort: 5000 # ต้องตรงกับ containerPort ใน Deployment และ app.py
      nodePort: 30001  # พอร์ตที่จะเปิดบนเครื่อง (เลือกเลขระหว่าง 30000-32767)